### ISSUE TITLE
adding cameras

### ISSUE THREAD

**Issue by martin-rizzi** [mnit-rtmc/monstream#4]
Hi! i'm having troubles adding cameras to the program. How can i do it?

**Comment by DougLau** [comment]
This program doesn't keep track of cameras on its own, only the currently playing stream(s).  It is designed to work with [IRIS](https://github.com/mnit-rtmc/iris), but the control [protocol](https://github.com/mnit-rtmc/monstream/blob/master/doc/protocol.md) is very simple.
